name: coffee-imbalance
channels: [conda-forge, defaults, pytorch]
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - imbalanced-learn=0.12.2
  - xgboost=2.0.3
  - pyts=0.13.0
  - tqdm=4.66.4
  - scipy=1.12.0
  - statsmodels=0.14.1
  - pytorch=2.2.1
  - torchvision=0.17.1
  - cpuonly
  - pip
  - pip:
      - joblib==1.3.2
      - mlflow==2.13.1
      - matplotlib==3.8.4
      - ruff==0.5.7
      - pytest==8.2.1
      - pytest-cov==5.0.0
      - mypy==1.10.0
